# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'speech_ui.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1280, 672)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setStyleSheet("QWidget#centralwidget{\n"
"background-color: #d3e1f7;\n"
"}")
        self.centralwidget.setObjectName("centralwidget")
        self.questions_frame = QtWidgets.QFrame(self.centralwidget)
        self.questions_frame.setGeometry(QtCore.QRect(330, 50, 581, 571))
        self.questions_frame.setStyleSheet("QFrame#questions_frame{\n"
"background-color: #eaf4ff;\n"
"border: 0px solid #eaf4ff;\n"
"border-radius: 45px;\n"
"}")
        self.questions_frame.setFrameShape(QtWidgets.QFrame.Box)
        self.questions_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.questions_frame.setObjectName("questions_frame")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.questions_frame)
        self.verticalLayout.setContentsMargins(30, 20, 30, 20)
        self.verticalLayout.setSpacing(6)
        self.verticalLayout.setObjectName("verticalLayout")
        self.pic_label = QtWidgets.QLabel(self.questions_frame)
        self.pic_label.setMinimumSize(QtCore.QSize(0, 230))
        self.pic_label.setMaximumSize(QtCore.QSize(16777215, 230))
        self.pic_label.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.pic_label.setText("")
        self.pic_label.setObjectName("pic_label")
        self.verticalLayout.addWidget(self.pic_label)
        self.question = QtWidgets.QLabel(self.questions_frame)
        self.question.setMinimumSize(QtCore.QSize(0, 110))
        self.question.setMaximumSize(QtCore.QSize(16777215, 100))
        self.question.setStyleSheet("font: 22pt \"Bahnschrift\";\n"
"color: #6d7b94;")
        self.question.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.question.setText("")
        self.question.setAlignment(QtCore.Qt.AlignCenter)
        self.question.setWordWrap(True)
        self.question.setObjectName("question")
        self.verticalLayout.addWidget(self.question)
        self.answer = QtWidgets.QLabel(self.questions_frame)
        self.answer.setMinimumSize(QtCore.QSize(0, 55))
        self.answer.setMaximumSize(QtCore.QSize(16777215, 65))
        self.answer.setStyleSheet("font: 26pt \"Bahnschrift\";\n"
"color: #a5b4c9;")
        self.answer.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.answer.setText("")
        self.answer.setAlignment(QtCore.Qt.AlignCenter)
        self.answer.setObjectName("answer")
        self.verticalLayout.addWidget(self.answer)
        self.record_label = QtWidgets.QLabel(self.questions_frame)
        self.record_label.setMinimumSize(QtCore.QSize(128, 128))
        self.record_label.setMaximumSize(QtCore.QSize(128, 128))
        self.record_label.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.record_label.setText("")
        self.record_label.setObjectName("record_label")
        self.verticalLayout.addWidget(self.record_label, 0, QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
